apiVersion: v1
description: Opal - helm stack (in BETA)
name: opal
version: 1.4.0
appVersion: 2.13
sources:
- https://github.com/lifecycle-project/datashield-helm.git
icon: https://raw.githubusercontent.com/lifecycle-project/datashield-helm/master/charts/opal/catalogIcon-opal.png
home: https://obiba.org
maintainers:
- name: sidohaakma
