dependencies:
  - name: mysql
    version: ^0.10.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
  - name: mongodb
    version: ^5.14.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mongodb.enabled
  - name: rserver
    version: ^1.2.5
    repository: https://registry.molgenis.org/repository/helm
    condition: rserver.enabled,rserver.embedded=false
    