dependencies:
  - name: mysql
    version: ^1.6.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
  - name: mongodb
    version: ^7.8.6
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mongodb.enabled
  - name: rserver
    version: ^1.2.5
    repository: https://registry.molgenis.org/repository/helm
    condition: rserver.standalone
