# Default values for molgenis.

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  host: opal.test.molgenis.org
  path: /
  tls: []

javaOpts:
  maxHeapSpace: "3g"
resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 4Gi
image:
  repository: registry.hub.docker.com
  name: obiba/opal
  tag: 2.13
  pullPolicy: Always
adminPassword: xxxxx
persistence:
  enabled: false
  user:
    storageClass: ""
    accessMode: ReadWriteMany
    size: 50Gi
    # existingClaim: ""
  app:
    storageClass: ""
    accessMode: ReadWriteMany
    size: 50Gi
    # existingClaim: ""

bootstrapper:
  image:
    repository: registry.molgenis.org
    name: datashield/opal-bootstrapper
    tag: latest
    pullPolicy: Always

rserver:
  enabled: true

mongodb:
  enabled: false
  usePassword: false
  persistence:
    enabled: false

mysql:
  enabled: false
  persistence:
    enabled: false
  mysqlRootPassword: xxxxx
  mysqlUser: opal
  mysqlPassword: xxxxx
  initializationFiles:
    opal-ids.sql: |-
      CREATE DATABASE IF NOT EXISTS opal_ids DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      GRANT ALL PRIVILEGES ON opal_ids.* TO "opal"@"%" IDENTIFIED BY "?opal01!";
      FLUSH PRIVILEGES;
    opal-data.sql: |-
      CREATE DATABASE IF NOT EXISTS opal_data DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      GRANT ALL PRIVILEGES ON opal_data.* TO "opal"@"%" IDENTIFIED BY "?opal01!";
      FLUSH PRIVILEGES;

nodeSelector: {
  deployPod: "true"
}

tolerations: []

affinity: {}
