apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "rserver.fullName" . }}
  labels:
    app: {{ template "rserver.name" . }}
    chart: {{ template "rserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rserver.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "rserver.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: rserver
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port.external }}
        - containerPort: {{ .Values.service.port.internal }}
        resources:
{{ toYaml .Values.resources | indent 10 }}

{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}