apiVersion: v1
kind: Service
metadata:
  name: {{ template "rserver.fullName" . }}
  labels:
    app: {{ template "rserver.name" . }}
    chart: {{ template "rserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rserve
      port: {{ .Values.service.port.rserve }}
    - name: rserver
      port: {{ .Values.service.port.rserver }}
  selector:
    app: {{ template "rserver.name" . }}
    release: {{ .Release.Name }}
