apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rstudio.fullname" . }}
  labels:
    app: {{ template "rstudio.name" . }}
    chart: {{ template "rstudio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rstudio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "rstudio.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{ if .Values.persistence.enabled }}
      initContainers:
      - name: rstudio-nfs
        image: busybox
        command: ["sh", "-c", "mkdir -p /home/rstudio/; chown -R 1000:1000 /home/rstudio"]
        volumeMounts:
         - name: pv-rstudio
           mountPath: "/home"
      {{- end }}
      containers:
      - name: rstudio
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PASSWORD
          value: "{{ .Values.adminPassword }}"
        - name: USERS
          value: "{{ .Values.users }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        {{ if .Values.persistence.enabled }}
        volumeMounts:
        - name: pv-rstudio
          mountPath: /home
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.port }}
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 25
          successThreshold: 1
        resources:
{{ toYaml .Values.resources | indent 12 }}

{{- if .Values.persistence.enabled }}
      volumes:
        - name: pv-rstudio
          persistentVolumeClaim:
            claimName: {{ include "rstudio.fullname" . }}
{{- end }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}