apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  name: {{ template "rstudio.fullname" . }}
  labels:
    app: {{ template "rstudio.name" . }}
    chart: {{ template "rstudio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rstudio.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "rstudio.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{ if .Values.persistence.enabled }}
      initContainers:
      - name: rstudio-nfs
        image: busybox
        command: ["sh", "-c", "mkdir -p /home/rstudio/; chown -R 1000:1000 /home/rstudio"]
        volumeMounts:
         - name: pv-rstudio
           mountPath: "/home"
      {{- end }}
      containers:
      {{- with .Values.rstudio }}
      - name: {{ .name }}
        image: "{{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        env:
        - name: PASSWORD
          value: "{{ .adminPassword }}"
        ports:
        - containerPort: {{ .service.port }}
        {{ if $.Values.persistence.enabled }}
        volumeMounts:
        - name: pv-rstudio
          mountPath: /home
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .service.port }}
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 25
          successThreshold: 1
      {{- end }}

{{- if .Values.persistence.enabled }}
      volumes:
        - name: pv-rstudio
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Values.rstudio.persistence.claim }}
{{- end }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}