apiVersion: v1
appVersion: "1.0"
description: RStudio stack
name: rstudio
version: 0.0.1
sources:
- https://git.webhosting.rug.nl/molgenis/thirdparty-ops-docker-helm.git
icon: https://raw.git.webhosting.rug.nl/molgenis/thirdparty-ops-docker-helm/master/charts/rstudio/catalog-molgenis-rstudio.svg
home: https://www.rocker.org
maintainers:
- name: sidohaakma
- name: fdlk
