# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: production

service:
  name: rstudio
  type: ClusterIP
  port: 8787

name: rstudio
strategy:
  type: Recreate
restartPolicy: Always
adminPassword: xxxxx
image:
  repository: registry.hub.docker.com
  name: molgenis/rstudio
  tag: 3.1.0
  pullPolicy: Always

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  }
  path: /
  hosts:
  - name: analysis.test.molgenis.org
  tls: []

persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteMany
  size: 50GB
  # existingClaim: ""

nodeSelector: {}

tolerations: []

affinity: {}
