# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: production

rstudio:
  name: rstudio
  strategy:
    type: Recreate
  restartPolicy: Always
  adminPassword: xxxxx
  persistence:
    size: 5Gi
    claim: pvc-rstudio
  image:
    repository: registry.hub.docker.com
    name: molgenis/rstudio
    tag: beta
    pullPolicy: Always

service:
  name: rstudio
  type: ClusterIP
  port: 8787

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  }
  path: /
  hosts:
  - name: analysis.test.molgenis.org
  tls: []

persistence:
  enabled: false
  retain: false


nodeSelector: {}

tolerations: []

affinity: {}
