# Default values for molgenis.

replicaCount: 1

service:
  type: ClusterIP
  port:
    rserver: 6312
    rserve: 6311

image:
  repository: registry.hub.docker.com
  name: obiba/opal-rserver
  tag: 1.5
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

nodeSelector: {
  deployPod: "true"
}

tolerations: []

affinity: {}
