jupyterhub:
  ingress:
    enabled: true
    hosts:
    - jupyter.edge.molgenis.org
  
  hub:
    # experiment as an admin on jupyter hub
    config:
      JupyterHub:
        admin_access: true
        authenticator_class: generic-oauth
      Authenticator:
        allowed_users:
          - s.haakma@umcg.nl
        admin_users: 
          - s.haakma@umcg.nl
        auto_login: false
      GenericOAuthenticator:
        client_id: xxxxxxxxxx-xxxxxxxxxxx-xxxxxxxxxxxx
        client_secret: xxxxxxxxxx-xxxxxxxxxxx-xxxxxxxxxxxx
        login_service: LifeCycle
        authorize_url: https://auth.molgenis.org/oauth2/authorize
        token_url: https://auth.molgenis.org/oauth2/token
        userdata_url: https://auth.molgenis.org/oauth2/userinfo
        userdata_method: GET      
        username_key: email
        oauth_callback_url: http://127.0.0.1/hub/oauth_callback
        scope: 
         - openid
         - name
         - profile
         - email

  singleuser:
    image:
      name: molgenis/rstudio-jupyter
      tag: '1.1.0'
    cpu:
      limit: 2
      guarantee: 1
    memory:
      limit: 1G
      guarantee: 1G
    startTimeout: 300
    extraEnv:
      PASSWORD: "admin"
      USER: "rstudio"
    profileList:
    - display_name: "DataSHIELD - dsBase v6.0 - default"
      description: "RStudio analysis environment with DataSHIELD | dsBase (v6.0.1)"
      kubespawner_override:
        image: molgenis/rstudio-jupyter:1.1.0
    - display_name: "DataSHIELD - dsBase v6.1"
      description: "RStudio analysis environment with DataSHIELD | dsBase (v6.1.0)"
      kubespawner_override:
        image: molgenis/rstudio-jupyter:1.2.0
    - display_name: "DataSHIELD - dsBase v6.1 / dsExposome v1.0"
      description: "RStudio analysis environment with DataSHIELD | dsBase (v6.1.0) | dsExposome (v1.0.1)"
      kubespawner_override:
        image: molgenis/rstudio-jupyter:1.3.3

  proxy:
    secretToken: xxxxxxxxxx-xxxxxxxxxxx-xxxxxxxxxxxx