apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "opal.fullname" . }}
  labels:
    app: {{ template "opal.name" . }}
    chart: {{ template "opal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "opal.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "opal.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      {{- if and .Values.rserver.enabled ( .Values.rserver.standalone ) }}
        - name: copy-config
          image: busybox
          command: ['sh', '-c', 'yes | cp /root/*.properties /data/.']
          volumeMounts:
            - name: opal-configmap
              mountPath: /root/
            - name: opal-configdir
              mountPath: /data/
      {{- end }}
      containers:
        - name: opal
      {{- if and .Values.rserver.enabled ( .Values.rserver.standalone ) }}
          lifecycle:
            postStart:
              exec:
                command: ['sh', '-c', 'yes | cp /data/*.properties /srv/conf/. && yes | cp /data/*.properties /usr/share/opal/conf/.;']
      {{- end }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OPAL_ADMINISTRATOR_PASSWORD
              value: "{{ .Values.adminPassword }}"
            - name: JAVA_OPTS
              value: -Xms{{ .Values.javaOpts.initHeapSpace }} -Xmx{{ .Values.javaOpts.maxHeapSpace }} -XX:MaxPermSize={{ .Values.javaOpts.maxPermSize }} -XX:+UseG1GC
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: pv-user
              mountPath: /home
            - name: pv-app
              mountPath: /var/lib/opal
            {{- if and .Values.rserver.enabled ( .Values.rserver.standalone ) }}
            - name: opal-configdir
              mountPath: /data
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 80
            periodSeconds: 5
            failureThreshold: 25
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
        {{- if and .Values.rserver.enabled ( not .Values.rserver.standalone ) }}
        - name: rserver
          image: registry.hub.docker.com/obiba/opal-rserver:{{ .Values.rserver.image.tag }}
          tag: 
          imagePullPolicy: Always
          ports:
            - containerPort: 6312
            - containerPort: 6311
          resources:
{{ toYaml .Values.rserver.resources | indent 12 }}
        {{- end }}

      volumes:
      {{- if and .Values.rserver.enabled ( .Values.rserver.standalone ) }}
        - name: opal-configdir
          emptyDir: {}
        - name: opal-configmap
          configMap:
            name: {{ template "opal.fullname" . }}-config
            key: opal-config.properties
      {{- end }}
        - name: pv-user
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "opal.fullname" . }}-user
      {{- else }}
          emptyDir: {}
      {{- end }}
        - name: pv-app
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "opal.fullname" . }}-app
      {{- else }}
          emptyDir: {}
      {{- end }}

  {{- with .Values.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
    {{- end }}
