{{- if and .Values.persistence.enabled (not .Values.persistence.app.existingClaim) -}}
apiVersion: extensions/v1beta1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opal.fullname" . }}-app
  labels:
    app.kubernetes.io/name: {{ include "opal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "opal.chart" . }}
  spec:
    accessModes:
      - {{ .Values.persistence.app.accessMode | quote }}
    resources:
      requests:
        storage: {{ .Values.persistence.app.size | quote }}
    {{- if .Values.persistence.app.storageClass }}
    {{- if (eq "-" .Values.persistence.app.storageClass) }}
    storageClassName: ""
    {{- else }}
    storageClassName: "{{ .Values.persistence.app.storageClass }}"
    {{- end }}
    {{- end }}
    {{- end }}