apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opal.fullname" . }}
  labels:
    app: {{ template "opal.name" . }}
    chart: {{ template "opal.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  adminpassword: {{ .Values.adminPassword | b64enc | quote }} 