apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.service.name }}"
  labels:
    app: "{{ .Release.Name }}-{{ .Values.service.name }}"
    chart: {{ template "opal.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "{{ .Release.Name }}-{{ .Values.service.name }}"
      port: {{ .Values.service.port }}
  selector:
    app: {{ template "opal.name" . }}
    release: {{ .Release.Name }}
